#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /config/.local/
chown -R vrs:vrs /config/.local

# Install operator photos
echo "Installing operator flags..."
mkdir -p /config/operatorflags/
cp -R /opt/VRS_Extras/bonesaviation/operator-logo-starter-pack/* /config/operatorflags
cp -R /opt/VRS_Extras/dedevillela/VRS-Operator-Flags/OperatorFlags/* /config/operatorflags
chown -R vrs:vrs /config/operatorflags

echo "Installing silhouettes..."
mkdir -p /config/silhouettes/
cp -R /opt/VRS_Extras/dedevillela/VRS-Silhouettes/Silhouettes/* /config/silhouettes/
chown -R vrs:vrs /config/silhouettes
