name: Docker Build and Push

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v1
      
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag sxb7006/docker-virtualradarserver:${{steps.vars.outputs.tag}}
        
      - name: Push the tagged Docker image
        run: docker push sxb7006/docker-virtualradarserver:${{steps.vars.outputs.tag}}
        
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag sxb7006/docker-virtualradarserver:latest
        
      - name: Push the latest Docker image
        run: docker push sxb7006/docker-virtualradarserver:latest
