name: Docker Build and Push

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: sxb1n9/docker-virtualradarserver
        
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag b1n9/docker-virtualradarserver:v3
        
      - name: Push the tagged Docker image
        run: docker push b1n9/docker-virtualradarserver:v3
        
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag b1n9/docker-virtualradarserver:latest
        
      - name: Push the latest Docker image
        run: docker push b1n9/docker-virtualradarserver:latest
